cloudhooks.hook:
  type: mapping
  mapping:
    label:
      type: label
      label: 'Label'
    plugin_id:
      type: text
      label: 'Plugin id'
    weight:
      type: integer
      label: 'Weight'

cloudhooks.environment.*:
  type: mapping
  mapping:
    label:
      type: label
      label: 'Environment label'
    description:
      type: text
      label: 'Description'
    hooks:
      type: sequence
      label: 'Hooks'
      sequence:
        type: cloudhooks.hook
